- name: variable task step-2
  hosts: localhost
  vars: 
   course: "devops"
   trainer: "siva"
   duration: "110hrs"
  tasks:
  - name: variables 
    vars:
     course: "aws devops"
    ansible.builtin.debug:
     msg: "iam learning {{course}},trainer is {{trainer}},duration {{duration}}" 

