- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
     name: "{{item}}" #here item keyword is default from ansible
     state: present
    loop:
    - git 
    - postfix