- name: advanced loop
  hosts: localhost
  become: yes
  tasks:
  - name: install and uninstall
    ansible.builtin.package:
     name: "{{item.name}}"
     state: "{{item.present}}"
    loop:
    - {name: 'git' , state: 'present'}
    - {name: 'postfix', state: 'absent'}